using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using MyEnquiry.Helper;
using MyEnquiry_BussniessLayer.Interface;
using MyEnquiry_BussniessLayer.ViewModels;
using MyEnquiry_DataLayer.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;

namespace MyEnquiry_BussniessLayer.Bussniess
{
    public class Bills:IBills
    {
        private IConfiguration _configuration;
        private MyAppContext _context;
        public static IWebHostEnvironment _environment;

        public Bills(IConfiguration configuration, MyAppContext context, IWebHostEnvironment environment)
        {
            _configuration = configuration;
            _context = context;
            _environment = environment;
        }

        public dynamic Get(ModelStateDictionary modelState, ClaimsPrincipal user)
        {
            var userId = user.FindFirstValue(ClaimTypes.NameIdentifier);
            var usera = _context.Users.Where(a => a.Id == userId && !a.Deleted);
            if (usera != null && usera.Any(a => a.CompanyId != null))
            {

                if ((usera.FirstOrDefault().UserType != 2 || usera.FirstOrDefault().CompanyId == null))
                {
                    modelState.AddModelError("غير مسموح", "غير مسموح لك باتمام هذه العملية");
                    return null;
                }
                var BillBank = _context.Cases.Include(a=>a.Bank).Where(a =>!a.Deleted&& a.CompanyId == usera.FirstOrDefault().CompanyId && a.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank&&!a.PaidFromBank).Select(q => new DuiesBank
                {
                    Id = q.BankId,
                    NameCompany = q.Bank.NameAr

                }).Distinct().Select(q => new DuiesBank
                {
                    Id = q.Id,
                    NameCompany=q.NameCompany
                   
                }).ToList();
            
                return BillBank;
            }
            return null;
        }
        public async Task<dynamic> Pay(ModelStateDictionary modelState, int Id, int date, ClaimsPrincipal user)
        {
            try
            {
                var userId = user.FindFirstValue(ClaimTypes.NameIdentifier);
                var usera = _context.Users.Where(a => a.Id == userId && !a.Deleted);
                if (usera != null && usera.Any(a => a.CompanyId == null))
                {
                    return null;
                }
                var listAll = _context.Cases.Where(a => !a.Deleted && a.BankId == Id && a.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !a.PaidFromBank && a.CompanyId == usera.FirstOrDefault().CompanyId && a.DoneFromBank.Month == date).Include(a => a.Bank).Include(a => a.Reviewer).Include(a => a.CaseStatus).Include(a => a.SuperVisor).Include(a => a.CaseType).ToList();
                foreach(var item in listAll)
                {
                    item.PaidFromBank = true;
                    _context.SaveChanges();
                }
                return new
                {
                    result = new
                    {

                    },
                    msg = "تم الدفع بنجاح "
                };
            }
               catch (Exception ex)
            {
                modelState.AddModelError("تحذير", "حدث خطأ ما");
                return null;
            }
        }
         public dynamic GetById(ModelStateDictionary modelState, int Id, ClaimsPrincipal user)
        {
            var userId = user.FindFirstValue(ClaimTypes.NameIdentifier);
            var usera = _context.Users.Where(a => a.Id == userId && !a.Deleted);
            if (usera != null && usera.Any(a => a.CompanyId != null))
            {
             var vm = new MonthVm();
                vm.NameBank = _context.Cases.Include(a=>a.Bank).Where(a => !a.Deleted && a.BankId == Id && a.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !a.PaidFromBank && a.CompanyId == usera.FirstOrDefault().CompanyId ).FirstOrDefault().Bank.NameAr;
                vm.Jan = _context.Cases.Where(a => !a.Deleted && a.BankId == Id && a.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !a.PaidFromBank&&a.CompanyId==usera.FirstOrDefault().CompanyId&&a.DoneFromBank.Month==1).Include(a => a.Bank).Include(a => a.Reviewer).Include(a => a.CaseStatus).Include(a => a.SuperVisor).Include(a => a.CaseType).Select(s => new DuiesBank
                {
                    DonefromReviewr=s.DoneFromBank,
                    NameCompany = s.HomeGovernorate ?? "",
                    TypeOfCases = s.CaseType.NameAr ?? "",
                    Texas = (_context.BankCompany.Include(a => a.Cities).Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id && a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && s.CompanyId == usera.FirstOrDefault().CompanyId).FirstOrDefault().PriceCase * 14* _context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.Company.NameAr == s.Company.NameAr && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank && c.DoneFromBank.Month == 1).Count()) / 100 ?? 0,
                    NumberOfCases = _context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.Company.NameAr == s.Company.NameAr && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank&&c.DoneFromBank.Month==1).Count(),
                    Price = _context.BankCompany.Include(a => a.Cities).Any(a => !a.Deleted && a.BanksId == Id && a.Cities.NameAr .Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && s.CompanyId == usera.FirstOrDefault().CompanyId && a.BanksId == Id) != false ? _context.BankCompany.Include(a => a.Cities).Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id && a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && s.CompanyId == usera.FirstOrDefault().CompanyId).FirstOrDefault().PriceCase : 0,
                    Total = _context.BankCompany.Include(a => a.Cities).Any(a => !a.Deleted && a.BanksId == Id && a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && s.CompanyId == usera.FirstOrDefault().CompanyId && a.BanksId == Id) != false ? (_context.BankCompany.Include(a => a.Cities).Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id && a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && a.BanksId == Id).FirstOrDefault().PriceCase * _context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.CompanyId == usera.FirstOrDefault().CompanyId && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank && c.DoneFromBank.Month == 1).Count()) : 0,
                    AfterTotal = (_context.BankCompany.Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id && a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId).FirstOrDefault().PriceCase) * 14 * (_context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.CompanyId == usera.FirstOrDefault().CompanyId && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank && c.BankId == Id && s.CompanyId == usera.FirstOrDefault().CompanyId).Count()) / 100 + (_context.BankCompany.Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id && a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId).FirstOrDefault().PriceCase)* (_context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.CompanyId == usera.FirstOrDefault().CompanyId && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank && c.BankId == Id && s.CompanyId == usera.FirstOrDefault().CompanyId && c.DoneFromBank.Month == 1).Count()) ?? 0,
                }).Distinct().ToList();
                vm.Feb = _context.Cases.Where(a => !a.Deleted && a.BankId == Id && a.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !a.PaidFromBank&&a.CompanyId==usera.FirstOrDefault().CompanyId && a.DoneFromBank.Month == 2).Include(a => a.Bank).Include(a => a.Reviewer).Include(a => a.CaseStatus).Include(a => a.SuperVisor).Include(a => a.CaseType).Select(s => new DuiesBank
                {
                    DonefromReviewr=s.DoneFromBank,
                    NameCompany = s.HomeGovernorate ?? "",
                    TypeOfCases = s.CaseType.NameAr ?? "",
                    Texas = (_context.BankCompany.Include(a => a.Cities).Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && s.CompanyId == usera.FirstOrDefault().CompanyId).FirstOrDefault().PriceCase * 14* _context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.Company.NameAr == s.Company.NameAr && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank && c.DoneFromBank.Month ==2).Count()) / 100 ?? 0,
                    NumberOfCases = _context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.Company.NameAr == s.Company.NameAr && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank&&c.DoneFromBank.Month==2).Count(),
                    Price = _context.BankCompany.Include(a => a.Cities).Include(a => a.Cities).Any(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && s.CompanyId == usera.FirstOrDefault().CompanyId && a.BanksId == Id) != false ? _context.BankCompany.Include(a => a.Cities).Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && s.CompanyId == usera.FirstOrDefault().CompanyId).FirstOrDefault().PriceCase : 0,
                    Total = _context.BankCompany.Include(a => a.Cities).Any(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && s.CompanyId == usera.FirstOrDefault().CompanyId && a.BanksId == Id) != false ? (_context.BankCompany.Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && a.BanksId == Id).FirstOrDefault().PriceCase * _context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.CompanyId == usera.FirstOrDefault().CompanyId && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank && c.DoneFromBank.Month == 2).Count()) : 0,
                    AfterTotal = (_context.BankCompany.Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId).FirstOrDefault().PriceCase) * 14 * (_context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.CompanyId == usera.FirstOrDefault().CompanyId && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank && c.BankId == Id && s.CompanyId == usera.FirstOrDefault().CompanyId).Count()) / 100 + (_context.BankCompany.Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId).FirstOrDefault().PriceCase)* (_context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.CompanyId == usera.FirstOrDefault().CompanyId && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank && c.BankId == Id && s.CompanyId == usera.FirstOrDefault().CompanyId && c.DoneFromBank.Month == 2).Count()) ?? 0,
                }).Distinct().ToList();    
               vm.MArc = _context.Cases.Where(a => !a.Deleted && a.BankId == Id && a.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !a.PaidFromBank&&a.CompanyId==usera.FirstOrDefault().CompanyId && a.DoneFromBank.Month == 3).Include(a => a.Bank).Include(a => a.Reviewer).Include(a => a.CaseStatus).Include(a => a.SuperVisor).Include(a => a.CaseType).Select(s => new DuiesBank
                {
                    DonefromReviewr=s.DoneFromBank,
                    NameCompany = s.HomeGovernorate ?? "",
                    TypeOfCases = s.CaseType.NameAr ?? "",
                    Texas = (_context.BankCompany.Include(a => a.Cities).Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && s.CompanyId == usera.FirstOrDefault().CompanyId).FirstOrDefault().PriceCase * 14* _context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.Company.NameAr == s.Company.NameAr && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank && c.DoneFromBank.Month ==3).Count()) / 100 ?? 0,
                    NumberOfCases = _context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.Company.NameAr == s.Company.NameAr && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank&&c.DoneFromBank.Month==3).Count(),
                    Price = _context.BankCompany.Include(a => a.Cities).Include(a => a.Cities).Any(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && s.CompanyId == usera.FirstOrDefault().CompanyId && a.BanksId == Id) != false ? _context.BankCompany.Include(a => a.Cities).Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && s.CompanyId == usera.FirstOrDefault().CompanyId).FirstOrDefault().PriceCase : 0,
                    Total = _context.BankCompany.Include(a => a.Cities).Any(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && s.CompanyId == usera.FirstOrDefault().CompanyId && a.BanksId == Id) != false ? (_context.BankCompany.Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && a.BanksId == Id).FirstOrDefault().PriceCase * _context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.CompanyId == usera.FirstOrDefault().CompanyId && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank && c.DoneFromBank.Month == 3).Count()) : 0,
                    AfterTotal = (_context.BankCompany.Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId).FirstOrDefault().PriceCase) * 14 * (_context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.CompanyId == usera.FirstOrDefault().CompanyId && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank && c.BankId == Id && s.CompanyId == usera.FirstOrDefault().CompanyId).Count()) / 100 + (_context.BankCompany.Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId).FirstOrDefault().PriceCase)* (_context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.CompanyId == usera.FirstOrDefault().CompanyId && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank && c.BankId == Id && s.CompanyId == usera.FirstOrDefault().CompanyId && c.DoneFromBank.Month == 3).Count()) ?? 0,
                }).Distinct().ToList();   
                vm.April = _context.Cases.Where(a => !a.Deleted && a.BankId == Id && a.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !a.PaidFromBank&&a.CompanyId==usera.FirstOrDefault().CompanyId &&a.DoneFromBank.Month==4).Include(a => a.Bank).Include(a => a.Reviewer).Include(a => a.CaseStatus).Include(a => a.SuperVisor).Include(a => a.CaseType).Select(s => new DuiesBank
                {
                    DonefromReviewr=s.DoneFromBank,
                    NameCompany = s.HomeGovernorate ?? "",
                    TypeOfCases = s.CaseType.NameAr ?? "",
                    Texas = (_context.BankCompany.Include(a => a.Cities).Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && s.CompanyId == usera.FirstOrDefault().CompanyId).FirstOrDefault().PriceCase * 14* _context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.Company.NameAr == s.Company.NameAr && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank && c.DoneFromBank.Month ==4).Count()) / 100 ?? 0,
                    NumberOfCases = _context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.Company.NameAr == s.Company.NameAr && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank&&c.DoneFromBank.Month==4).Count(),
                    Price = _context.BankCompany.Include(a => a.Cities).Include(a => a.Cities).Any(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && s.CompanyId == usera.FirstOrDefault().CompanyId && a.BanksId == Id) != false ? _context.BankCompany.Include(a => a.Cities).Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && s.CompanyId == usera.FirstOrDefault().CompanyId).FirstOrDefault().PriceCase : 0,
                    Total = _context.BankCompany.Include(a => a.Cities).Any(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && s.CompanyId == usera.FirstOrDefault().CompanyId && a.BanksId == Id) != false ? (_context.BankCompany.Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && a.BanksId == Id).FirstOrDefault().PriceCase * _context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.CompanyId == usera.FirstOrDefault().CompanyId && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank && c.DoneFromBank.Month ==4).Count()) : 0,
                    AfterTotal = (_context.BankCompany.Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId).FirstOrDefault().PriceCase) * 14 * (_context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.CompanyId == usera.FirstOrDefault().CompanyId && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank && c.BankId == Id && s.CompanyId == usera.FirstOrDefault().CompanyId).Count()) / 100 + (_context.BankCompany.Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId).FirstOrDefault().PriceCase)* (_context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.CompanyId == usera.FirstOrDefault().CompanyId && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank && c.BankId == Id && s.CompanyId == usera.FirstOrDefault().CompanyId && c.DoneFromBank.Month == 4).Count()) ?? 0,
                }).Distinct().ToList();   
                vm.May = _context.Cases.Where(a => !a.Deleted && a.BankId == Id && a.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !a.PaidFromBank&&a.CompanyId==usera.FirstOrDefault().CompanyId && a.DoneFromBank.Month == 5).Include(a => a.Bank).Include(a => a.Reviewer).Include(a => a.CaseStatus).Include(a => a.SuperVisor).Include(a => a.CaseType).Select(s => new DuiesBank
                {
                    DonefromReviewr=s.DoneFromBank,
                    NameCompany = s.HomeGovernorate ?? "",
                    TypeOfCases = s.CaseType.NameAr ?? "",
                    Texas = (_context.BankCompany.Include(a => a.Cities).Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && s.CompanyId == usera.FirstOrDefault().CompanyId).FirstOrDefault().PriceCase * 14* _context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.Company.NameAr == s.Company.NameAr && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank && c.DoneFromBank.Month ==5).Count()) / 100 ?? 0,
                    NumberOfCases = _context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.Company.NameAr == s.Company.NameAr && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank&&c.DoneFromBank.Month==5).Count(),
                    Price = _context.BankCompany.Include(a => a.Cities).Include(a => a.Cities).Any(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && s.CompanyId == usera.FirstOrDefault().CompanyId && a.BanksId == Id) != false ? _context.BankCompany.Include(a => a.Cities).Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && s.CompanyId == usera.FirstOrDefault().CompanyId).FirstOrDefault().PriceCase : 0,
                    Total = _context.BankCompany.Include(a => a.Cities).Any(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && s.CompanyId == usera.FirstOrDefault().CompanyId && a.BanksId == Id) != false ? (_context.BankCompany.Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && a.BanksId == Id).FirstOrDefault().PriceCase * _context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.CompanyId == usera.FirstOrDefault().CompanyId && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank && c.DoneFromBank.Month == 5).Count()) : 0,
                    AfterTotal = (_context.BankCompany.Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId).FirstOrDefault().PriceCase) * 14 * (_context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.CompanyId == usera.FirstOrDefault().CompanyId && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank && c.BankId == Id && s.CompanyId == usera.FirstOrDefault().CompanyId).Count()) / 100 + (_context.BankCompany.Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId).FirstOrDefault().PriceCase)* (_context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.CompanyId == usera.FirstOrDefault().CompanyId && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank && c.BankId == Id && s.CompanyId == usera.FirstOrDefault().CompanyId && c.DoneFromBank.Month ==5).Count()) ?? 0,
                }).Distinct().ToList();  
                vm.Jun = _context.Cases.Where(a => !a.Deleted && a.BankId == Id && a.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !a.PaidFromBank&&a.CompanyId==usera.FirstOrDefault().CompanyId && a.DoneFromBank.Month == 6).Include(a => a.Bank).Include(a => a.Reviewer).Include(a => a.CaseStatus).Include(a => a.SuperVisor).Include(a => a.CaseType).Select(s => new DuiesBank
                {
                    DonefromReviewr=s.DoneFromBank,
                    NameCompany = s.HomeGovernorate ?? "",
                    TypeOfCases = s.CaseType.NameAr ?? "",
                    Texas = (_context.BankCompany.Include(a => a.Cities).Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && s.CompanyId == usera.FirstOrDefault().CompanyId ).FirstOrDefault().PriceCase * 14* _context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.Company.NameAr == s.Company.NameAr && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank && c.DoneFromBank.Month ==6).Count()) / 100 ?? 0,
                    NumberOfCases = _context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.Company.NameAr == s.Company.NameAr && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank&&c.DoneFromBank.Month==6).Count(),
                    Price = _context.BankCompany.Include(a => a.Cities).Include(a => a.Cities).Any(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && s.CompanyId == usera.FirstOrDefault().CompanyId && a.BanksId == Id) != false ? _context.BankCompany.Include(a => a.Cities).Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && s.CompanyId == usera.FirstOrDefault().CompanyId).FirstOrDefault().PriceCase : 0,
                    Total = _context.BankCompany.Include(a => a.Cities).Any(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && s.CompanyId == usera.FirstOrDefault().CompanyId && a.BanksId == Id) != false ? (_context.BankCompany.Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && a.BanksId == Id).FirstOrDefault().PriceCase * _context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.CompanyId == usera.FirstOrDefault().CompanyId && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank && c.DoneFromBank.Month == 6).Count()) : 0,
                    AfterTotal = (_context.BankCompany.Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId).FirstOrDefault().PriceCase) * 14 * (_context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.CompanyId == usera.FirstOrDefault().CompanyId && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank && c.BankId == Id && s.CompanyId == usera.FirstOrDefault().CompanyId).Count()) / 100 + (_context.BankCompany.Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId).FirstOrDefault().PriceCase)* (_context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.CompanyId == usera.FirstOrDefault().CompanyId && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank && c.BankId == Id && s.CompanyId == usera.FirstOrDefault().CompanyId && c.DoneFromBank.Month ==6).Count()) ?? 0,
                }).Distinct().ToList();  
                vm.Jul = _context.Cases.Where(a => !a.Deleted && a.BankId == Id && a.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !a.PaidFromBank&&a.CompanyId==usera.FirstOrDefault().CompanyId && a.DoneFromBank.Month == 7).Include(a => a.Bank).Include(a => a.Reviewer).Include(a => a.CaseStatus).Include(a => a.SuperVisor).Include(a => a.CaseType).Select(s => new DuiesBank
                {
                    DonefromReviewr=s.DoneFromBank,
                    NameCompany = s.HomeGovernorate ?? "",
                    TypeOfCases = s.CaseType.NameAr ?? "",
                    Texas = (_context.BankCompany.Include(a => a.Cities).Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && s.CompanyId == usera.FirstOrDefault().CompanyId ).FirstOrDefault().PriceCase * 14* _context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.Company.NameAr == s.Company.NameAr && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank && c.DoneFromBank.Month ==7).Count()) / 100 ?? 0,
                    NumberOfCases = _context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.Company.NameAr == s.Company.NameAr && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank&&c.DoneFromBank.Month==7).Count(),
                    Price = _context.BankCompany.Include(a => a.Cities).Include(a => a.Cities).Any(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && s.CompanyId == usera.FirstOrDefault().CompanyId && a.BanksId == Id) != false ? _context.BankCompany.Include(a => a.Cities).Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && s.CompanyId == usera.FirstOrDefault().CompanyId).FirstOrDefault().PriceCase : 0,
                    Total = _context.BankCompany.Include(a => a.Cities).Any(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && s.CompanyId == usera.FirstOrDefault().CompanyId && a.BanksId == Id) != false ? (_context.BankCompany.Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && a.BanksId == Id).FirstOrDefault().PriceCase * _context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.CompanyId == usera.FirstOrDefault().CompanyId && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank && c.DoneFromBank.Month == 7).Count()) : 0,
                    AfterTotal = (_context.BankCompany.Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId).FirstOrDefault().PriceCase) * 14 * (_context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.CompanyId == usera.FirstOrDefault().CompanyId && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank && c.BankId == Id && s.CompanyId == usera.FirstOrDefault().CompanyId).Count()) / 100 + (_context.BankCompany.Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId).FirstOrDefault().PriceCase)* (_context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.CompanyId == usera.FirstOrDefault().CompanyId && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank && c.BankId == Id && s.CompanyId == usera.FirstOrDefault().CompanyId && c.DoneFromBank.Month ==7).Count()) ?? 0,
                }).Distinct().ToList();  
                vm.Agu = _context.Cases.Where(a => !a.Deleted && a.BankId == Id && a.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !a.PaidFromBank&&a.CompanyId==usera.FirstOrDefault().CompanyId && a.DoneFromBank.Month == 8).Include(a => a.Bank).Include(a => a.Reviewer).Include(a => a.CaseStatus).Include(a => a.SuperVisor).Include(a => a.CaseType).Select(s => new DuiesBank
                {
                    DonefromReviewr=s.DoneFromBank,
                    NameCompany = s.HomeGovernorate ?? "",
                    TypeOfCases = s.CaseType.NameAr ?? "",
                    Texas = (_context.BankCompany.Include(a => a.Cities).Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && s.CompanyId == usera.FirstOrDefault().CompanyId ).FirstOrDefault().PriceCase * 14* _context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.Company.NameAr == s.Company.NameAr && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank && c.DoneFromBank.Month ==8).Count()) / 100 ?? 0,
                    NumberOfCases = _context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.Company.NameAr == s.Company.NameAr && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank&&c.DoneFromBank.Month==8).Count(),
                    Price = _context.BankCompany.Include(a => a.Cities).Include(a => a.Cities).Any(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && s.CompanyId == usera.FirstOrDefault().CompanyId && a.BanksId == Id) != false ? _context.BankCompany.Include(a => a.Cities).Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && s.CompanyId == usera.FirstOrDefault().CompanyId).FirstOrDefault().PriceCase : 0,
                    Total = _context.BankCompany.Include(a => a.Cities).Any(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && s.CompanyId == usera.FirstOrDefault().CompanyId && a.BanksId == Id) != false ? (_context.BankCompany.Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && a.BanksId == Id).FirstOrDefault().PriceCase * _context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.CompanyId == usera.FirstOrDefault().CompanyId && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank && c.DoneFromBank.Month == 8).Count()) : 0,
                    AfterTotal = (_context.BankCompany.Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId).FirstOrDefault().PriceCase) * 14 * (_context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.CompanyId == usera.FirstOrDefault().CompanyId && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank && c.BankId == Id && s.CompanyId == usera.FirstOrDefault().CompanyId).Count()) / 100 + (_context.BankCompany.Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId).FirstOrDefault().PriceCase)* (_context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.CompanyId == usera.FirstOrDefault().CompanyId && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank && c.BankId == Id && s.CompanyId == usera.FirstOrDefault().CompanyId && c.DoneFromBank.Month ==8).Count()) ?? 0,
                }).Distinct().ToList();
                vm.Sept = _context.Cases.Where(a => !a.Deleted && a.BankId == Id && a.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !a.PaidFromBank&&a.CompanyId==usera.FirstOrDefault().CompanyId && a.DoneFromBank.Month == 9).Include(a => a.Bank).Include(a => a.Reviewer).Include(a => a.CaseStatus).Include(a => a.SuperVisor).Include(a => a.CaseType).Select(s => new DuiesBank
                {
                    DonefromReviewr=s.DoneFromBank,
                    NameCompany = s.HomeGovernorate ?? "",
                    TypeOfCases = s.CaseType.NameAr ?? "",
                    Texas = (_context.BankCompany.Include(a => a.Cities).Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && s.CompanyId == usera.FirstOrDefault().CompanyId ).FirstOrDefault().PriceCase * 14* _context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.Company.NameAr == s.Company.NameAr && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank && c.DoneFromBank.Month ==8).Count()) / 100 ?? 0,
                    NumberOfCases = _context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.Company.NameAr == s.Company.NameAr && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank&&c.DoneFromBank.Month==9).Count(),
                    Price = _context.BankCompany.Include(a => a.Cities).Include(a => a.Cities).Any(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && s.CompanyId == usera.FirstOrDefault().CompanyId && a.BanksId == Id) != false ? _context.BankCompany.Include(a => a.Cities).Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && s.CompanyId == usera.FirstOrDefault().CompanyId).FirstOrDefault().PriceCase : 0,
                    Total = _context.BankCompany.Include(a => a.Cities).Any(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && s.CompanyId == usera.FirstOrDefault().CompanyId && a.BanksId == Id) != false ? (_context.BankCompany.Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && a.BanksId == Id).FirstOrDefault().PriceCase * _context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.CompanyId == usera.FirstOrDefault().CompanyId && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank && c.DoneFromBank.Month == 9).Count()) : 0,
                    AfterTotal = (_context.BankCompany.Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId).FirstOrDefault().PriceCase) * 14 * (_context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.CompanyId == usera.FirstOrDefault().CompanyId && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank && c.BankId == Id && s.CompanyId == usera.FirstOrDefault().CompanyId).Count()) / 100 + (_context.BankCompany.Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId).FirstOrDefault().PriceCase)* (_context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.CompanyId == usera.FirstOrDefault().CompanyId && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank && c.BankId == Id && s.CompanyId == usera.FirstOrDefault().CompanyId && c.DoneFromBank.Month ==9).Count()) ?? 0,
                }).Distinct().ToList();    
                vm.oct = _context.Cases.Where(a => !a.Deleted && a.BankId == Id && a.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !a.PaidFromBank&&a.CompanyId==usera.FirstOrDefault().CompanyId && a.DoneFromBank.Month == 10).Include(a => a.Bank).Include(a => a.Reviewer).Include(a => a.CaseStatus).Include(a => a.SuperVisor).Include(a => a.CaseType).Select(s => new DuiesBank
                {
                    DonefromReviewr=s.DoneFromBank,
                    NameCompany = s.HomeGovernorate ?? "",
                    TypeOfCases = s.CaseType.NameAr ?? "",
                    Texas = (_context.BankCompany.Include(a => a.Cities).Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && s.CompanyId == usera.FirstOrDefault().CompanyId ).FirstOrDefault().PriceCase * 14* _context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.Company.NameAr == s.Company.NameAr && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank && c.DoneFromBank.Month ==10).Count()) / 100 ?? 0,
                    NumberOfCases = _context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.Company.NameAr == s.Company.NameAr && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank&&c.DoneFromBank.Month==10).Count(),
                    Price = _context.BankCompany.Include(a => a.Cities).Include(a => a.Cities).Any(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && s.CompanyId == usera.FirstOrDefault().CompanyId && a.BanksId == Id) != false ? _context.BankCompany.Include(a => a.Cities).Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && s.CompanyId == usera.FirstOrDefault().CompanyId).FirstOrDefault().PriceCase : 0,
                    Total = _context.BankCompany.Include(a => a.Cities).Any(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && s.CompanyId == usera.FirstOrDefault().CompanyId && a.BanksId == Id) != false ? (_context.BankCompany.Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && a.BanksId == Id).FirstOrDefault().PriceCase * _context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.CompanyId == usera.FirstOrDefault().CompanyId && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank && c.DoneFromBank.Month == 10).Count()) : 0,
                    AfterTotal = (_context.BankCompany.Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId).FirstOrDefault().PriceCase) * 14 * (_context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.CompanyId == usera.FirstOrDefault().CompanyId && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank && c.BankId == Id && s.CompanyId == usera.FirstOrDefault().CompanyId).Count()) / 100 + (_context.BankCompany.Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId).FirstOrDefault().PriceCase)* (_context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.CompanyId == usera.FirstOrDefault().CompanyId && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank && c.BankId == Id && s.CompanyId == usera.FirstOrDefault().CompanyId && c.DoneFromBank.Month ==10).Count()) ?? 0,
                }).Distinct().ToList(); 
                vm.Nuv = _context.Cases.Where(a => !a.Deleted && a.BankId == Id && a.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !a.PaidFromBank&&a.CompanyId==usera.FirstOrDefault().CompanyId && a.DoneFromBank.Month == 10).Include(a => a.Bank).Include(a => a.Reviewer).Include(a => a.CaseStatus).Include(a => a.SuperVisor).Include(a => a.CaseType).Select(s => new DuiesBank
                {
                    DonefromReviewr=s.DoneFromBank,
                    NameCompany = s.HomeGovernorate ?? "",
                    TypeOfCases = s.CaseType.NameAr ?? "",
                    Texas = (_context.BankCompany.Include(a => a.Cities).Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && s.CompanyId == usera.FirstOrDefault().CompanyId ).FirstOrDefault().PriceCase * 14* _context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.Company.NameAr == s.Company.NameAr && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank && c.DoneFromBank.Month ==11).Count()) / 100 ?? 0,
                    NumberOfCases = _context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.Company.NameAr == s.Company.NameAr && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank&&c.DoneFromBank.Month==11).Count(),
                    Price = _context.BankCompany.Include(a => a.Cities).Include(a => a.Cities).Any(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && s.CompanyId == usera.FirstOrDefault().CompanyId && a.BanksId == Id) != false ? _context.BankCompany.Include(a => a.Cities).Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && s.CompanyId == usera.FirstOrDefault().CompanyId).FirstOrDefault().PriceCase : 0,
                    Total = _context.BankCompany.Include(a => a.Cities).Any(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && s.CompanyId == usera.FirstOrDefault().CompanyId && a.BanksId == Id) != false ? (_context.BankCompany.Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && a.BanksId == Id).FirstOrDefault().PriceCase * _context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.CompanyId == usera.FirstOrDefault().CompanyId && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank && c.DoneFromBank.Month ==11).Count()) : 0,
                    AfterTotal = (_context.BankCompany.Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId).FirstOrDefault().PriceCase) * 14 * (_context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.CompanyId == usera.FirstOrDefault().CompanyId && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank && c.BankId == Id && s.CompanyId == usera.FirstOrDefault().CompanyId).Count()) / 100 + (_context.BankCompany.Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId).FirstOrDefault().PriceCase)* (_context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.CompanyId == usera.FirstOrDefault().CompanyId && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank && c.BankId == Id && s.CompanyId == usera.FirstOrDefault().CompanyId && c.DoneFromBank.Month ==11).Count()) ?? 0,
                }).Distinct().ToList();  
                vm.Dec = _context.Cases.Where(a => !a.Deleted && a.BankId == Id && a.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !a.PaidFromBank&&a.CompanyId==usera.FirstOrDefault().CompanyId && a.DoneFromBank.Month == 10).Include(a => a.Bank).Include(a => a.Reviewer).Include(a => a.CaseStatus).Include(a => a.SuperVisor).Include(a => a.CaseType).Select(s => new DuiesBank
                {
                    DonefromReviewr=s.DoneFromBank,
                    NameCompany = s.HomeGovernorate ?? "",
                    TypeOfCases = s.CaseType.NameAr ?? "",
                    Texas = (_context.BankCompany.Include(a => a.Cities).Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && s.CompanyId == usera.FirstOrDefault().CompanyId ).FirstOrDefault().PriceCase * 14* _context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.Company.NameAr == s.Company.NameAr && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank && c.DoneFromBank.Month ==12).Count()) / 100 ?? 0,
                    NumberOfCases = _context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.Company.NameAr == s.Company.NameAr && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank&&c.DoneFromBank.Month==12).Count(),
                    Price = _context.BankCompany.Include(a => a.Cities).Include(a => a.Cities).Any(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && s.CompanyId == usera.FirstOrDefault().CompanyId && a.BanksId == Id) != false ? _context.BankCompany.Include(a => a.Cities).Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && s.CompanyId == usera.FirstOrDefault().CompanyId).FirstOrDefault().PriceCase : 0,
                    Total = _context.BankCompany.Include(a => a.Cities).Any(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && s.CompanyId == usera.FirstOrDefault().CompanyId && a.BanksId == Id) != false ? (_context.BankCompany.Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId && a.BanksId == Id).FirstOrDefault().PriceCase * _context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.CompanyId == usera.FirstOrDefault().CompanyId && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank && c.DoneFromBank.Month == 12).Count()) : 0,
                    AfterTotal = (_context.BankCompany.Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId).FirstOrDefault().PriceCase) * 14 * (_context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.CompanyId == usera.FirstOrDefault().CompanyId && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank && c.BankId == Id && s.CompanyId == usera.FirstOrDefault().CompanyId).Count()) / 100 + (_context.BankCompany.Include(a => a.Cities).Where(a => !a.Deleted && a.BanksId == Id &&a.Cities.NameAr.Contains(s.HomeGovernorate) && a.CaseTypesId == s.CaseTypeId).FirstOrDefault().PriceCase)* (_context.Cases.Where(c => c.HomeGovernorate == s.HomeGovernorate && c.CompanyId == usera.FirstOrDefault().CompanyId && s.CaseStatusId == (int)CaseEnumStatus.AcceptedFromBank && !s.PaidFromBank && c.BankId == Id && s.CompanyId == usera.FirstOrDefault().CompanyId && c.DoneFromBank.Month ==12).Count()) ?? 0,
                }).Distinct().ToList();
                 
                return vm;
            }

           throw null;
        }

       
    }
}
